config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do
    resources :reviews, only: [ :show, :create, :destroy ]
  end

  resources :users, only: [ :new, :create, :show, :edit, :update ]
  resources :sessions, only: [ :new, :create, :destroy ]
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews

  validates :name, presence: true
  validates :price_in_cents, numericality: { only_integer: true }

  def formatted_price
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("%.2f", price_in_dollars )
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :reviews
  has_many :products, through: :reviews

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find( session[ :user_id ] ) if session[ :user_id ]
  end

  def ensure_logged_in
    unless current_user
      flash[ :alert ]= "Please log in"
      redirect_to new_session_url
    end
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
      @products = if params[ :search ]
        Product.where( "LOWER(name) LIKE LOWER ( ? )", "%#{ params[ :search ] }%" )
      else
        @products = Product.all
    end

    respond_to do | format |
      format.html
      format.js
    end

    # if request.xhr?
    #   render @products
    # end
  end

  def show
    @product = Product.find( params[ :id ] )

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find( params[ :id ] )
  end

  def create
    @product = Product.new( product_params )

    if @product.save
      redirect_to products_url
    else
      render :new
    end

  end

  def update
    @product = Product.find( params[ :id ] )

    if @product.update_attributes( product_params )
      redirect_to product_url( @product )
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find( params[ :id ] )
    @product.destroy
    redirect_to products_url
  end

  private

  def product_params
    params.require( :product ).permit( :name, :description, :price_in_cents )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :load_product
  before_action :ensure_logged_in, only: [ :create, :destroy ]


  def show
    @review = Review.find( params[ :id ] )
  end

  def create
    @review = @product.reviews.build( review_params )
    @review.user = current_user

    if @review.save
      redirect_to products_url, notice: "Review created successfully"
    else
      render "products/show"
    end
  end

  def destroy
    @review = Review.find( params[ :id ])
    @review.destroy
  end

  private

  def review_params
    params.require( :review ).permit( :comment, :product_id )
  end

  def load_product
    @product = Product.find( params[ :product_id ] )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by( email: params[ :email ] )
    if user && user.authenticate( params[ :password ] )
      session[ :user_id ] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[ :alert ] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[ :user_id ] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      redirect_to products_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find( params[ :id ] )
  end

  def edit
    @user = User.find( params[ :id ] )
  end

  def update
    @user = User.find( params[ :id ] )

    if @user.update_attributes( user_params )
      redirect_to user_url( @user )
    else
      render :edit
    end
  end

  def destroy
    @user.find( params[ :id ] )
  end

  private

  def user_params
    params.require( :user ).permit( :email, :name, :password, :password_confirmation )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Rainforest</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
    </head>
    <body>

      <p>
        <% if current_user %>
          Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path( "current" ), :method => :delete %>.  <%= link_to "Profile", "/users/#{ session[ :user_id ] }" %>
        <% else %>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        <% end %>
      </p>

      <% if flash[ :notice ]%>
        <p>
          <%= flash[ :notice ] %>
        </p>
      <% end %>
      <% if flash[ :alert ] %>
        <p>
          <%= flash[ :alert ] %>
        </p>
      <% end %>

      <%= yield %>

    </body>
</html>

app/views/products/_form.html.erb
<%= form_for( @product ) do | f | %>
<% if @product.errors.any? %>
<h4><%= pluralize( @product.errors.count, "error") %>
    prohibited this product from being saved:
</h4>
<% end %>
<ul>
    <% @product.errors.full_messages.each do | msg | %>
    <li>
        <%= msg %>
    </li>
    <% end %>
</ul>
<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.label :description %>
    <%= f.text_area :description %>
</p>
<p>
    <%= f.label :price_in_cents %>
    <%= f.number_field :price_in_cents %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/products/_product.html.erb
<% @products.each do | p | %>
    <p>
      <%= link_to p.name, "/products/#{ p.id }" %>
    </p>
    <p>
        <%= p.description %>
    </p>
    <p>
        <%= p.formatted_price %>
    </p>
<% end %>

app/views/products/edit.html.erb
<h1>Product <%= @product.name %></h1>

<%= form_for @product do | p | %>

<%= render "form" %>

<% end %>

app/views/products/index.html.erb
<h1>All Products</h1>

<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
  <%= text_field_tag :search, params[ :search ] %>
  <%= submit_tag "Search" %>
  <% end %>

<div id="products">
  <%= render @products %>
</div>

<% if current_user %>
  <%= link_to "New", new_product_path %>
<% end %>

<!-- <script type="text/javascript">
  function display_search_results() {
    // readyState === 4 means that the asyncronous request completed successfully
    if ( this.readyState  === 4 ) {
      console.log( this );
      document.getElementById( 'products' ).innerHTML = this.responseText;
    }
  }

  var form = document.getElementById( 'search-form' );
  form.addEventListener( 'submit', function( event ) {
    event.preventDefault();
    var searchValue = document.getElementById( 'search' ).value;

    var xhr = new XMLHttpRequest();
    xhr.onload = display_search_results;
    xhr.open( 'GET', '/products?search=' + searchValue, true );
    xhr.setRequestHeader( "X-Requested-With", "XMLHttpRequest" );
    xhr.send();
  });
</script> -->

app/views/products/index.js.erb
$( '#products' ).html( "<%= j ( render @products ) %>" );

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "form" %>

<%= link_to "Back", products_path %>

app/views/products/show.html.erb
<h1>Product
    <%= @product.name %>
</h1>
<p>
    <%= @product.description %>
</p>
<p>
    <%= @product.formatted_price %>
</p>

<p>
    <%= link_to "Back", products_path %>
</p>

  <% if current_user %>
    <p>
      <%= link_to "Edit", edit_product_path %>
    </p>
  <% else %>
    <p>
      Please log in to edit product.
    </p>
  <% end %>


<h4>Reviews</h4>

<p>
  Reviews for <%= @product.name %>
</p>

<% @product.reviews.reverse.each do | review | %>
  <p>
    <%= review.comment %>

  <% if review.user != nil %>
  <em> by <%= review.user.email %> </em>
  Added on: <%= review.created_at %>
  <% end %>

  </p>
<% end %>


<% if current_user %>
  <h4>New Review</h4>

  <%= form_for( [ @product, @review ] ) do | f | %>
    <% if @review.errors.any? %>
      <h2><%= pluralize( @review.errors.count, "error" ) %>
          prohibited this review from being saved:</h2>
      <ul>
          <% @review.errors.full_messages.each do | msg | %>
          <li>
              <% msg %>
          </li>
          <% end %>
      </ul>
    <% end %>

    <p>
        <%= f.label :comment %>
        <%= f.text_area :comment %>
    </p>
    <p>
        <%= f.submit %>
    </p>
  <% end %>

  <% else %>

  <p>
      Please
      <%= link_to "log in", new_session_path %>
      to add a review.
  </p>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

app/views/reviews/show.html.erb
<h4>Reviews#show</h4>

app/views/users/_form.html.erb
<%= form_for( @user ) do | f | %>
<% if @user.errors.any? %>
<h4><%= pluralize( @user.errors.count, "error") %>
    prohibited this product from being saved:
</h4>
<% end %>
<ul>
    <% @user.errors.full_messages.each do | msg | %>
    <li>
        <%= msg %>
    </li>
    <% end %>
</ul>
<p>
    <%= f.label :email %>
    <%= f.text_field :email %>
</p>
<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
</p>
<p>
    <%= f.submit %>
</p>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>

<%= form_for @user do | p | %>

<%= render "form" %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do | f | %>
  <% if @user.errors.any? %>
  <h4>Form is invalid</h4>
  <ul>
      <% @user.errors.full_messages.each do | msg | %>
      <li>
          <%= msg %>
      </li>
      <% end %>
  </ul>
  <% end %>

  <p>
      <%= f.label :email %>
      <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
      <%= f.label :password %>
      <%= f.password_field :password %>
  </p>
  <p>
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
  </p>
  <p>
      <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<h1>User Profile <%= @user.name %></h1>
<p>
  <%= @user.email %>
</p>
<p>
  <%= @user.name %>
</p>
<%= link_to 'Back', url_for( :back ) %> <%= link_to 'Edit', edit_user_path %>